CREATE TABLE USERS (USER_ID INT IDENTITY(1001,1), USERNAME VARCHAR, PASSWORD VARCHAR, enabled tinyint, PRIMARY KEY (USER_ID));
CREATE TABLE GAMES (GAME_ID INT IDENTITY(5001,1), TIMES_PLAYED INT, NUMBER_TO_GUESS VARCHAR, USERNAME VARCHAR, CREATED_DATE VARCHAR, LAST_MODIFIED_DATE VARCHAR, FINISHED TINYINT, PRIMARY KEY (GAME_ID));
CREATE TABLE ATTEMPTS (ATTEMPT_ID INT IDENTITY(7001,1), BULLS INT, COWS INT, CURRENT_NUMBER VARCHAR, GAME_ID INT, PRIMARY KEY (ATTEMPT_ID), FOREIGN KEY (GAME_ID) REFERENCES GAMES(GAME_ID))

