CREATE TABLE USERS (USER_ID INT IDENTITY(1001,1), USERNAME VARCHAR, PASSWORD VARCHAR, enabled tinyint, PRIMARY KEY (USER_ID));
CREATE TABLE GAMES (GAME_ID INT IDENTITY(5001,1), TIMES_PLAYED INT, NUMBER_TO_GUESS INT, USERNAME VARCHAR, CREATED_DATE DATE, LAST_MODIFIED_DATE DATE, FINISHED TINYINT, PRIMARY KEY (GAME_ID));

